# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('rain-propagation', ['core'])
    module.source = [
        'model/rain-propagation.cc',
        'helper/rain-propagation-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('rain-propagation')
    module_test.source = [
        'test/rain-propagation-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'rain-propagation'
    headers.source = [
        'model/rain-propagation.h',
        'helper/rain-propagation-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

